### ISSUE TITLE
Section 2.2 - Automatable checks (David MacDonald)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#45]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0008
## Original Comment

Would like to see a line that only about 14%-20% of WCAG can be evaluated automatically, in the best of circumstances.

**Comment by nitedog** [comment]
## Resolution

Partial - mentioned in rewording of section 2.2.2. However, I would suggest not to put any figures unless we have a mechanism of calculating these figures. Otherwise we can just say something like "only few accessibility requirements can be tested fully automatically", as we do in section 2.2.2. See also Issue #11
